Added Bridge Option

diff --git a/piratebox/piratebox/init.d/piratebox_router b/piratebox/piratebox/init.d/piratebox_router
--- a/piratebox/piratebox/init.d/piratebox_router
+++ b/piratebox/piratebox/init.d/piratebox_router
@@ -76,6 +76,19 @@ case "$1" in
          start-stop-daemon -m -S -b -p $PIDFILE_HOSTAPN  -x /usr/sbin/hostapd --  $CONF_APN
          echo  $?
        fi
+
+      #BRIDGE
+      if [ -n $BRIDGE ] ; then
+         echo "Adding $INTERFACE to bridge $BRIDGE //  brctl addif 
+$BRIDGE  $INTERFACE "
+         sleep 1
+         BR_CMD="brctl addif  $BRIDGE  $INTERFACE"
+         ( $BR_CMD ; )
+         if  [ $? -ne 0 ] ;  then
+           echo "failed :( "
+         fi
+      fi
+
        if [ "$USE_DNSMASQ" = "yes" ] ;  then
          echo  "Starting dnsmasq... "
    # pidfile is written by dnsmasq
@@ -135,6 +148,18 @@ case "$1" in
      if [ "$DO_IW" = "yes" ] ; then
        iw dev $INTERFACE del
      fi
+
+      #BRIDGE
+      if [ -n $BRIDGE ] ; then
+         echo "Remove  $INTERFACE to bridge $BRIDGE //  brctl addif 
+$BRIDGE  $INTERFACE "
+         sleep 1
+         BR_CMD="brctl delif  $BRIDGE  $INTERFACE"
+         ( $BR_CMD ; )
+         if  [ $? -ne 0 ] ;  then
+           echo "failed :( "
+         fi
+      fi
 
 
      # Stop Chatservice
