created imageboard branch on top of lighttpd

diff --git a/piratebox_lighttpd/piratebox/init.d/piratebox_router b/piratebox_lighttpd/piratebox/init.d/piratebox_router
--- a/piratebox_lighttpd/piratebox/init.d/piratebox_router
+++ b/piratebox_lighttpd/piratebox/init.d/piratebox_router
@@ -33,13 +33,6 @@ CONF_LIGHTTPD=$PIRATEBOX/conf/lighttpd/lighttpd.conf
 #Some extra config files for dnsmasq
 CONF_HOSTS=$PIRATEBOX/conf/hosts
 
-## Set permissions and tmp folder
-mkdir -p $PIRATEBOX/share/tmp
-chown nobody:nogroup $PIRATEBOX/share -R
-chmod  u+rw $PIRATEBOX/share
-chown nobody:nogroup $PIRATEBOX/www -R
-chmod u+x $PIRATEBOX/www/cgi-bin/* 
-chown nobody:nogroup $PIRATEBOX/tmp
 
 if [ -f $CONF ] ; then
    . $CONF 
@@ -75,6 +68,18 @@ case "$1" in
          start-stop-daemon -m -S -b -p $PIDFILE_HOSTAPN  -x /usr/sbin/hostapd --  $CONF_APN
          echo $?
        fi
+
+      #BRIDGE
+      if [ -n $BRIDGE ] ; then
+         echo "Adding $INTERFACE to bridge $BRIDGE //  brctl addif $BRIDGE  $INTERFACE "
+         sleep 1
+         BR_CMD="brctl addif  $BRIDGE  $INTERFACE"
+         ( $BR_CMD ; )
+         if  [ $? -ne 0 ] ;  then
+           echo "failed :( "
+         fi
+      fi
+
        if [ "$USE_DNSMASQ" = "yes" ] ;  then
          echo  "Starting dnsmasq... "
    # pidfile is written by dnsmasq
@@ -87,8 +92,7 @@ case "$1" in
        start-stop-daemon -S -q  -p $PIDFILE_LIGHTTPD -x /usr/sbin/lighttpd -- -f $CONF_LIGHTTPD 
        echo $?
 
-       #Writing init-message and reset chat..
-       echo $CHATMSG > $CHATFOLDER/cgi-bin/data.pso  
+
      fi
 
     ;;
@@ -112,11 +116,24 @@ case "$1" in
 
 
      #Remove tmp files (depend. to droopy)
-     rm -f  "$FOLDER/tmp/*"
+     #rm -f  "$FOLDER/tmp/*"
 
-     if [ "$DO_IFCONFIG" = yes ] ; then
+     if [ "$DO_IFCONFIG" = "yes" ] ; then
        piratebox_setup_wlan.sh $CONF stop
      fi
+
+      #BRIDGE
+      if [ -n $BRIDGE ] ; then
+         echo "Removing $INTERFACE from bridge $BRIDGE //  brctl delif $BRIDGE  $INTERFACE "
+         sleep 1
+         BR_CMD="brctl delif  $BRIDGE  $INTERFACE"
+         ( $BR_CMD ; )
+         if  [ $? -ne 0 ] ;  then
+           echo "failed :( "
+         fi
+      fi
+
+
 
     ;;
   *)
